-- Supabase Database Schema
-- Run this SQL in your Supabase project's SQL Editor

-- Exercise sessions table
CREATE TABLE IF NOT EXISTS exercise_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  session_id TEXT NOT NULL,
  exercise_type TEXT NOT NULL,
  rep_count INTEGER DEFAULT 0,
  form_score DECIMAL(5,2) DEFAULT 0,
  duration_seconds INTEGER DEFAULT 0,
  feedback TEXT[],
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_exercise_sessions_user_id ON exercise_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_exercise_sessions_created_at ON exercise_sessions(created_at DESC);

-- User profiles table
CREATE TABLE IF NOT EXISTS user_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT UNIQUE NOT NULL,
  name TEXT,
  fitness_level TEXT DEFAULT 'beginner',
  goals TEXT[],
  preferences JSONB DEFAULT '{}',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE exercise_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;

-- Create policies (allow users to access only their own data)
CREATE POLICY "Users can view own exercise sessions" 
  ON exercise_sessions FOR SELECT 
  USING (auth.uid()::text = user_id);

CREATE POLICY "Users can insert own exercise sessions" 
  ON exercise_sessions FOR INSERT 
  WITH CHECK (auth.uid()::text = user_id);

CREATE POLICY "Users can update own profiles" 
  ON user_profiles FOR ALL 
  USING (auth.uid()::text = user_id);

-- If you want to allow anonymous/local users (no auth required), use this simpler setup:
-- For local-only mode, remove the RLS policies or create a simpler version

-- Simple view for checking storage (run separately if needed)
-- SELECT pg_size_pretty(pg_database_size(current_database()));
